[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
safe_harbor = "AE3K1g3QPY45R9u2aPyk5r1pVXHPUEF6UNAP76QHJi4L"

[programs.devnet]
safe_harbor = "64Gpb6dztgGMcWPkQrDV4VjFHSfXTPoDtrhEu8ykXFKU"

[programs.testnet]
safe_harbor = "AE3K1g3QPY45R9u2aPyk5r1pVXHPUEF6UNAP76QHJi4L"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "Devnet"
wallet = "./owner-keypair.json"
